name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-north-1
  ECR_REPO: 611837360680.dkr.ecr.eu-north-1.amazonaws.com/myapp

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPO:${{ github.sha }} .
      
      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REPO:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        run: |
          cd infra
          terraform init -input=false

      - name: Terraform apply
        env:
          IMAGE_URI: ${{ env.ECR_REPO }}:${{ github.sha }}
        run: |
          cd infra
          terraform apply -auto-approve -var "image_uri=$IMAGE_URI"
